// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/4/2026, 11:30:32 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ishabanov/Code/scrum-poker-web/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/plugins/**/*.{js,ts,mjs}","/Users/ishabanov/Code/scrum-poker-web/frontend/composables/**/*.{js,ts,mjs}","/Users/ishabanov/Code/scrum-poker-web/frontend/utils/**/*.{js,ts,mjs}","/Users/ishabanov/Code/scrum-poker-web/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ishabanov/Code/scrum-poker-web/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;