name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: What to build
        required: true
        default: both
        type: choice
        options:
          - frontend
          - backend
          - both
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  backend:
    if: ${{ inputs.build == 'backend' || inputs.build == 'both' || inputs.build == '' }}
    uses: ./.github/workflows/backend-build.yml

  frontend:
    if: ${{ inputs.build == 'frontend' || inputs.build == 'both' || inputs.build == '' }}
    uses: ./.github/workflows/frontend-build.yml
