name: Build

on:
  workflow_call:
    inputs:
      build:
        description: What to build
        required: true
        default: both
        type: choice
        options:
          - frontend
          - backend
          - both
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  go-tests:
    uses: ./.github/workflows/go-tests.yml

  go-cs:
    uses: ./.github/workflows/go-code-style.yml

  backend:
    if: ${{ inputs.build == 'backend' || inputs.build == 'both' }}
    needs: [go-tests, go-cs]
    uses: ./.github/workflows/backend-build.yml

  frontend:
    if: ${{ inputs.build == 'frontend' || inputs.build == 'both' }}
    uses: ./.github/workflows/frontend-build.yml
