name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  backend:
    uses: ./.github/workflows/backend-build.yml

  frontend:
    uses: ./.github/workflows/frontend-build.yml
